<a href="https://colab.research.google.com/github/crismunoz/Fuzzy-Logic/blob/master/LF_Composition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install -U scikit-learn
!pip install scikit-fuzzy

In [ ]:
from skfuzzy import maxmin_composition,maxprod_composition
import numpy as np

In [ ]:

P_xy = np.array(P_xy)

Q_yz = np.array(Q_yz)

PoQ_maxmin = maxmin_composition(P_xy,Q_yz)
PoQ_maxprod = maxprod_composition(P_xy,Q_yz)
print('PoQ_maxmin=',PoQ_maxmin)
print()
print('PoQ_maxprod=',PoQ_maxprod)

PoQ_maxmin= [[0.2 1.  0.8 0.8]
 [1.  0.5 0.6 0.5]
 [0.5 0.9 0.8 1. ]]

PoQ_maxprod= [[0.2 1.  0.8 0.8]
 [1.  0.5 0.6 0.5]
 [0.5 0.9 0.8 1. ]]


In [ ]:
umm_xy = np.array(umm_xy)

ump_yz = np.array(ump_yz)
u_R_maxmin = maxmin_composition(umm_xy, ump_yz)
u_R_maxprod = maxprod_composition(umm_xy, ump_yz)

print('u_R_maxmin=', u_R_maxmin)
print()
print('u_R_maxprod=', u_R_maxprod)

u_R_maxmin= [[0.6 0.8 0.5]
 [0.  0.4 0. ]
 [0.7 0.9 0.7]]

u_R_maxprod= [[0.42 0.72 0.35]
 [0.   0.32 0.  ]
 [0.63 0.81 0.56]]


In [ ]:
umm_xy = np.array(umm_xy)

ump_yz = np.array(ump_yz)
u_R_maxmin = maxmin_composition(umm_xy, ump_yz)
u_R_maxprod = maxprod_composition(umm_xy, ump_yz)

print('u_R_maxmin=', u_R_maxmin)
print()
print('u_R_maxprod=', u_R_maxprod)

In [ ]:
R_carateristicas_vs_casas = np.array(R_carateristicas_vs_casas)
R_caracteristicas_comprador = np.array(R_caracteristicas_comprador)
u_R = maxmin_composition(R_caracteristicas_comprador, R_carateristicas_vs_casas)